# Generated by Django 4.0.2 on 2022-04-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeeksModel',
            new_name='AddModel',
        ),
    ]
