# Generated by Django 4.0.2 on 2022-04-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_geeksmodel_addmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmodel',
            name='description',
            field=models.CharField(default='', max_length=20),
        ),
    ]
